services:
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - 5433:5432
    networks:
      - nutrify-network
    env_file:
      - .env
    volumes:
      - postgres-volume:/var/lib/postgresql/data

  node:
    container_name: node
    build: .
    networks:
      - nutrify-network
    ports:
      - 5000:5000
    depends_on:
      - postgres
    env_file:
      - .env

networks:
  nutrify-network:
    name: nutrify-network
    driver: bridge

volumes:
  postgres-volume:
